version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
        - '27017:27017'
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
        - '5000:5000'
    environment:
      - CONFIG_MONGODB_ADMINUSERNAME=root
      - CONFIG_MONGODB_ADMINPASSWORD=example
      - CONFIG_MONGODB_ADMINDB=Parser
